name    'puppet-subscription_manager'
version '0.0.1'
source 'git://github.com/jlaska/puppet-subscription_manager.git'
author 'James Laska <jlaska@redhat.com>'
license 'Apache License, Version 2.0'
summary 'subscription_manager provider for Puppet'
description 'This module provides Custom Providers for Red Hat Network Registering.'
project_page 'https://github.com/jlaska/puppet-subscription_manager'
dependency 'adrienthebo/puppet-boolean', '>=0.9.0'
